#!/bin/bash
#
# ifplugd.action script for unexicon
#
# $1 is the interface name
# $2 is either "up" or "down"


case "$2" in
	up)
        echo "Executing unexicon.action $@" >&2
		;;
	down)
        echo "Executing unexicon.action $@" >&2
		;;
esac

exit 0

# vim: ft=sh ts=4 et sw=4:
